### ISSUE TITLE
Linux Build Script: Long Int given; Int expected

### ISSUE THREAD

**Issue by circular** [shogundevel/shark#1]
Running the Linux build script returns an issue. Attempting flag -Wno-errors in script results in same output blocking build. Thanks for your time.

```
In file included from cshark/cshark_main.c:29:
cshark/cshark_system.c: In function ‘shark_lib_itos’:
cshark/cshark_system.c:407:37: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
  407 |     size_t length = sprintf(itos, "%d", SHARK_AS_INT(args[0]));
      |                                    ~^
      |                                     |
      |                                     int
      |                                    %ld
cshark/cshark_system.c: In function ‘shark_string_format’:
cshark/cshark_system.c:666:45: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
  666 |                 repr_size = sprintf(temp, "%d", SHARK_AS_INT(value));
      |                                            ~^
      |                                             |
      |                                             int
      |                                            %ld
```

**Comment by shogundevel** [comment]
Thanks, i will dive into it tonight. BTW wich distro are you using? Shark is tested in Mint 2x 64-bits and all tests passed so far.

Try opening the script, which is a single line long, and appending the option to remove warnings as errors to the command.

**Comment by circular** [comment]
> Thanks, i will dive into it tonight. BTW wich distro are you using? Shark is tested in Mint 2x 64-bits and all tests passed so far.

It's Ubuntu 20.04 LTS x64 here. I haven't tried some of the other distros on different machines here yet, and unfortunately this one is LTS but also the oldest I have on hand.

> Try opening the script, which is a single line long, and appending the option to remove warnings as errors to the command.

Unfortunately that's how I'm getting the results as posted. Thanks for your attention to this.

**Comment by gardhr** [comment]
The warning is related to inconsistencies in C's handling of int64_t in xprintf format strings;`%jd` is synonymous with the somewhat less portable `PRId64` macro. (#4)

**Comment by shogundevel** [comment]
Fixed it so far. This was an older issue i fixed already some time ago, did not commit though O _ O U
Also, new binaries for linux are provided (bin/shark and bin/gameshark) both tested and working on Mint 21
Now to build them fresh run the scripts as usual.
Thanks for your patience!

**Comment by shogundevel** [comment]
Mark, I dont know what youre doing with shark but, Do you liked using it so
far? If not, what would improve your experience? Thanks for your time in
advance.

**Comment by circular** [comment]
Thanks for your message. I tried the latest release today, and I appreciate your attention to the build script. 

The build script seemed to run without any output, so I'm guessing that's a success. However I wasn't sure what to do from there; I tried running "shark" but it didn't work, and anyway I'm thinking it's not really an installer, right?

Next I went into bin/ and ran `./shark aa.shk` with aa.shk being the code for a complete program at the end of Chapter 1.8. This gives me the message "can't locate archive". I searched the repo for that string and found it, but I haven't yet figured out what it means in context.

I also tried `wine ./shark.exe aa.shk` and got the same message. 

I looked in the Handbook for any kind of tips on compiling and necessary arguments or archives, but wasn't able to locate that kind of material.

I did search for "shk" and learned that GS uses a project layout. Even though it's a different application, I wondered if the shark compiler is looking for such a project folder/layout to be archived and passed as an argument to `shark` instead of the source file directly? This would explain to me why it mentions an archive, but I'm not sure what kind of archive format it may be looking for--maybe zip, tar, lzh, lha, rar, etc.

I wondered if it could be that Shark is meant for more experienced C programmers, but thought I'd run this all by you anyway, see if you can offer any tips. Maybe I'm just moments away from seeing Hello Marc on my console. :-) Thanks!

**Comment by shogundevel** [comment]
Most your issues come from my mistake, i dont made clear in the docs how to
actually use shark. The instructions are in the 'guide' file, not in the
handbook O _ O U. I gess merging both files would make things more clear
but i wanted the handbook to be sort of the spec of the language. The
missing archive error happens when shark(.exe) is unable to find the
system.shar or gameshark.shar archives it needs to run. See if these files
are present under the same directory of the executable.
You have the point when you say shark is designed for C programmers, you
will find why while reading the 'guide' file.
To test that shark is installed properly run the command '> shark tool', it
should print some text to the screen.
If the issue of not finding the archives persist, make another issue and we
will find the cause.
Cheers!

**Comment by shogundevel** [comment]
Hi, Marc. Some changes are made that migth solve the missing archive issue.
Try updating your install with the latest fixes and test it. Run 'shark
tool' to see how to use shark tools further.

Thanks for your patience.

**Comment by circular** [comment]
Thank you. I expect to have some time to try it out later this week or on the weekend. I will look forward to trying it out, and playing some tetris too...

**Comment by shogundevel** [comment]
Good to hear. By the time you try it i may ended writting sharkemu, an
emulator that lets you REPL in the command line and execute code without
building!

**Comment by shogundevel** [comment]
It has been a time now, and Shark just got to version 2.1

Im curious, did you give up with Shark? If so, why?

**Comment by circular** [comment]
Hi there,

Congratulations on 2.1! I really hope to continue my Shark journey :-) But to be sure, life has thrown in some challenges here recently. I'm looking forward to checking it out further as soon as I can!

Best,

Marc
