### ISSUE TITLE
sharkedit won't start

### ISSUE THREAD

**Issue by pro9code** [shogundevel/shark#13]
Am I doing something wrong?

```powershell
shark-2.2.0\bin\shuriken.exe edit
```
type error (render expected) at argument 1 of 'render.draw'.
call stack trace (most recent call first):
        module shuriken.render class render function draw
        module sharkedit class main_activity function render

**Comment by shogundevel** [comment]
Nothing wrong, it was a bug in sharkedit.shk. Now fixed. Thanks and welcome!
