### ISSUE TITLE
Failure to compile on Linux x64 (current Linux Mint)

### ISSUE THREAD

**Issue by Eirikur** [shogundevel/shark#7]
Errors first, then GCC version info at bottom.
=================================

In file included from cshark/cshark_main.c:29:
cshark/cshark_system.c: In function ‘shark_lib_itos’:
cshark/cshark_system.c:407:37: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
  407 |     size_t length = sprintf(itos, "%d", SHARK_AS_INT(args[0]));
      |                                    ~^
      |                                     |
      |                                     int
      |                                    %ld
cshark/cshark_system.c: In function ‘shark_string_format’:
cshark/cshark_system.c:666:45: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
  666 |                 repr_size = sprintf(temp, "%d", SHARK_AS_INT(value));
      |                                            ~^
      |                                             |
      |                                             int
      |                                            %ld

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.3.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-xKiWfi/gcc-11-11.3.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04) 
eh@tma-1 ~/Downloads/shark-1.0.0 $

**Comment by shogundevel** [comment]
This issue is fixed, use the latest version of the repo which also provides prebuilt binaries for mint. The code and build script are updated.

Will keep this issue open in case you find further problems running shark on linux or building from the script.

Thanks for your patience!

**Comment by Eirikur** [comment]
Totally clean build now!  You can close it!

**Comment by shogundevel** [comment]
I dont know what youre doing with shark but, Do you liked using it so far?
If not, what would improve your experience?
